### PR TITLE
Merge context-aware changes

### PR DESCRIPTION
**Pull request by csett86**
Includes all other upstream commits from https://github.com/octalmage/robotjs:master as well

### CODE REVIEW

**Review by saghul — APPROVED** [review]
LGTM, if this works let's store the pre builds in jitsi/robotjs please.

Also, do we need to change the package name or is Electron smart enough to pick the prebuilts from here?

**Comment by csett86** [comment]
Electron is smart enough if I had not fumbled the repo name yesterday. Will fix it this evening, please do not merge yet.

**Comment by csett86** [comment]
This is now ready to go, just includes all upstream and my context-aware changes.

Will push the repo rename and a refactoring to Node-API for the prebuilds separately.

**Comment by csett86** [comment]
The followup PRs are:

Rename: #4 
Node-API with prebuilds: #5

**Pull request merged**
