### PR TITLE
ci: automate npm publishing

### PR DESCRIPTION
**Pull request by csett86**
Requires npm access token in GH secret NPM_TOKEN

### CODE REVIEW

**Comment by csett86** [comment]
@saghul would you mind taking a look and adding the required NPM access token as github secret `NPM_TOKEN`

**Comment by saghul** [comment]
Sure thing, sorry I missed this one.

**Comment by saghul** [comment]
Done.

**Comment by csett86** [comment]
Can you please recheck the secret, publishing to npm failed with https://github.com/jitsi/robotjs/runs/4224164321?check_suite_focus=true

**Comment by csett86** [comment]
Forget it, my mistake, I missed setting the registry URL, now done

**Comment by saghul** [comment]
Ah, cool!

**Pull request merged**
